name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gdown
        run: pip install gdown

      - name: Download file from Google Drive
        run: |
          gdown --id 12qU9yPeiv_Cg42Kbwad6_iugAjMFlrWw --output ./data/ResNet152V2-Weather-Classification-03.h5

      - name: Verify downloaded file
        run: ls -l ./data

      
      - name: Copy model to Docker context
        run: |
          cp ./data/ResNet152V2-Weather-Classification-03.h5 ./data/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tarifasalma/dockerization-with-github-actions:latest

