name:  Build, Push Docker Image and Run Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gdown
        run: pip install gdown

      - name: Download file from Google Drive
        run: |
          mkdir -p ./data
          gdown --id 12qU9yPeiv_Cg42Kbwad6_iugAjMFlrWw --output ./data/ResNet152V2-Weather-Classification-03.h5

      - name: Verify downloaded file
        run: ls -l ./data

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tarifasalma/dockerization-with-github-actions:latest

      - name: Pull Docker image
        run: docker pull tarifasalma/dockerization-with-github-actions:latest

      - name: Run Docker container with mounted volumes
        run: |
         docker run \
           -v ${{ github.workspace }}/data:/app/data \
           -v ${{ github.workspace }}/output:/app/output \
           tarifasalma/datascience_industrialization:latest
